cursor none
cursor_text_color #000000
cursor_shape_unfocused beam
cursor_beam_thickness 1
cursor_trail 1
cursor_trail_decay 0.1 0.1
cursor_trail_start_threshold 2
scrollback_indicator_opacity 0.0

dynamic_background_opacity yes
notify_on_cmd_finish always
confirm_os_window_close 0

background_opacity 1
background_blur 0

foreground #ffffff
#background #767676
background #000000

window_margin_width 15

#The 256 terminal colors. There are 8 basic colors, each color has a
#dull and bright version, for the first 16 colors. You can set the
#remaining 240 colors as color16 to color255.

#bright #color
#dull

font_size 25.0

color9 #f2201f #red
color1 #cc0403

color10 #23fd00 #green
color2  #19cb00

color11 #fffd00 #yellow
color3  #cecb00


color12 #1a8fff #blue
color4  #0d73cc

color13 #fd28ff #magenta
color5  #cb1ed1 

color14 #14ffff #cyan
color6  #0dcdcd

color15 #ffffff #white
color7  #dddddd

color0 #000000 #black
color8 #767676
