
require("variables&rules")
require("functions")
require("/lookandfeel/lookandfeel")
require("/lookandfeel/animations")
require("binds/binds")
require("binds/backend")
require("binds/movewindow")
require("binds/movefocus")

require("workspaces/specialworkspaces/audiosettings")
require("workspaces/specialworkspaces/browser")
require("workspaces/specialworkspaces/email")
require("workspaces/specialworkspaces/gamelauncher")
require("workspaces/specialworkspaces/messenger")
require("workspaces/specialworkspaces/music")
require("workspaces/specialworkspaces/notes")
require("workspaces/specialworkspaces/terminal")
require("workspaces/specialworkspaces/terminal2")
require("workspaces/specialworkspaces/terminal3")

