wallpaper {
    monitor = $MON1
    path = ~/Pictures/myart/black.png
    fit_mode = cover
}

wallpaper {
    monitor = $MON2
    path = ~/Pictures/myart/newluciferwallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor = $MON3
    path = ~/Pictures/myart/black.png
    fit_mode = cover
}
splash = false
